id: 2915
set: 15
action: resource/update
name: modx-resource-settings
description: null
container: modx-resource-tabs
rule: tabTitle
value: 'Основная информация'
constraint_class: modResource
rank: 3
