id: 2538
set: 23
action: resource/create
name: modx-page-settings-right-box-left
description: null
container: modx-resource-tabs
rule: tabVisible
value: '0'
constraint_class: modResource
for_parent: 1
rank: 2
