id: 4727
set: 28
action: resource/update
name: modx-page-settings-right-box-left
description: null
container: modx-resource-tabs
rule: tabVisible
value: '0'
constraint: '3'
constraint_field: id
constraint_class: modResource
rank: 2
