id: 4726
set: 28
action: resource/update
name: modx-page-settings-right
description: null
container: modx-resource-tabs
rule: tabVisible
value: '0'
constraint: '3'
constraint_field: id
constraint_class: modResource
rank: 2
